# Generated by Django 3.0.5 on 2020-05-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('education', models.IntegerField(blank=True, null=True)),
                ('hometown', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('telphone', models.CharField(blank=True, max_length=255, null=True)),
                ('seniority', models.IntegerField(blank=True, null=True)),
                ('basic_wage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engineer',
                'managed': False,
            },
        ),
    ]
